server:
  port: 8092
  servlet:
    context-path: /consumer

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: statistic

kafka:
  server: localhost:9092
  group:
    id: server.broadcast
